### ISSUE TITLE
Accessing to a property of a relation if model name is singular does not work

### ISSUE THREAD

**Issue by ferjm** [mozilla-sensorweb/sensorthings#121]
A request like GET Things(1)/Locations/name does not work. GET Things(1)/name works ok though.

**Comment by ferjm** [comment]
Wrong example. GET http://localhost:8080/v1.0/Datastreams(3)/Thing/name is a better one.

**Comment by isabelrios** [comment]
Should not be the request: GET http://localhost:8080/v1.0/Datastreams(3)/Thing(1)/name
in order to access the property of a particular relation, otherwise what would be the response?
Currently that actually works.

**Comment by ferjm** [comment]
Some relations are accessed through the model singular name instead of model(id). A Datastream can only have one Thing, so Datastreams(id)/Thing is valid.
