### ISSUE TITLE
Reject requests with duplicated associations

### ISSUE THREAD

**Issue by ferjm** [mozilla-sensorweb/sensorthings#135]
From https://github.com/mozilla-sensorweb/sensorthings/blob/master/src/models/db.js#L251

>  // The spec does not specifically mention this, but in order to avoid
      // confussion, we forbid the case where an association is done in both
      // the URL and the request body. So for example, a request like this is
      // not valid.
      //
      // POST v1.0/Things(1)/Locations
      // {
      //   Thing: {
      //     '@iot.id': 1
      //   }
// }

**Comment by albertopq** [comment]
This should be already working, and covered in:

https://github.com/albertopq/sensorthings/blob/632a9eab6c532a5590b012b702bd2c45025ef4b6/test/test_datastreams.js#L33
