### ISSUE TITLE
It is possible to create more than one Location for a Thing with same encodingType

### ISSUE THREAD

**Issue by isabelrios** [mozilla-sensorweb/sensorthings#141]
Not sure if this would be a bug. Adding question label to clarify.

http://docs.opengeospatial.org/is/15-078r6/15-078r6.html#25

> The Location entity locates the Thing. Multiple Things MAY be located at the same Location. A Thing MAY not have a Location. A Thing SHOULD have only one Location.

However, in some complex use cases, a Thing MAY have more than one Location representations. In such case, the Thing MAY have more than one Locations. These Locations SHALL have different encodingTypes and the encodingTypes SHOULD be in different spaces (e.g., one encodingType in Geometrical space and one encodingType in Topological space).

For example:
1-Create a Thing:
curl -X POST -H "Content-Type: application/json" -H "Cache-Control: no-cache" -d '{
  "description": "A SensorWeb thing",
  "name":"SensorWebThing",
  "properties": {
    "organization": "Mozilla",
    "owner": "Mozilla"
  }
}' "http://localhost:8080/v1.0/Things"

2-Create a Location associated to the Thing
curl -X POST -H "Content-Type: application/json" -H "Cache-Control: no-cache" -d '{
    "description": "My backyard",
    "name": "My backyard",
    "encodingType": "application/vnd.geo+json",
    "location": {
        "type": "Point",
        "coordinates": [-117.123, 54.123]
    }
}' "http://localhost:8080/v1.0/Things(1)/Locations"

3-Create a different location to the same thing just changing the coordinates
curl -X POST -H "Content-Type: application/json" -H "Cache-Control: no-cache" -d '{
    "description": "My backyard",
    "name": "My backyard",
    "encodingType": "application/vnd.geo+json",
    "location": {
        "type": "Point",
        "coordinates": [-119.111, 54.222]
    }
}' "http://localhost:8080/v1.0/Things(1)/Locations"

**Comment by ferjm** [comment]
Good catch! This is indeed a bug.

**Comment by ferjm** [comment]
Fixed by #221
