### ISSUE TITLE
Publish OGC test results to AWS S3

### ISSUE THREAD

**Issue by ferjm** [mozilla-sensorweb/sensorthings#163]
The OGC tests suite generates some html files with the results of the test run. It would be extremely helpful if we could publish these html files to AWS.

**Comment by ferjm** [comment]
Fixed by #162

**Comment by ferjm** [comment]
gh-pages migth be easier http://stackoverflow.com/questions/12343452/how-to-publish-artifacts-in-travis-ci

**Comment by isabelrios** [comment]
Closed by #181
