### ISSUE TITLE
[Query options] Implement multi-level relations for $expand.

### ISSUE THREAD

**Issue by ferjm** [mozilla-sensorweb/sensorthings#185]
We need to support queries like `http://example.org/v1.0/Things?$expand=Datastreams/ObservedProperty` as defined in the standard:

> Additionally, each navigation property can be followed by a forward slash and another navigation property to enable identifying a multi-level relationship.

**Comment by isabelrios** [comment]
Would these cases, adding a system query option, also be covered by this issue?:
Ex:
http://example.org/v1.0/Datastreams(1)?$expand=Observations($filter=result eq 1) 
http://example.org/v1.0/Datastreams(1)?$expand=Observations($orderby=result) 
...
Or should we open a new issue? 
Currently the response is:
{"code":400,"errno":104,"error":"Bad Request","message":"$expand"}

**Comment by albertopq** [comment]
Hey @isabelrios, the test cases you are pointing at won't work after this fix. This issue is only for allowing requests like:

`/Datastreams(1)?$expand=Observations/FeaturesOfInterest`

Thanks!

**Comment by ferjm** [comment]
Fixed by #224
