### ISSUE TITLE
Accept PUT http requests

### ISSUE THREAD

**Issue by albertopq** [mozilla-sensorweb/sensorthings#190]
Test method putEntities:
                    Error during updating(PUT) of entity THING expected [200] but found [404]

**Comment by ferjm** [comment]
The spec says:

> Services MAY additionally support PUT...

So someone is lying here :\

I would file a bug in the spec.

**Comment by albertopq** [comment]
There is already one issue in the spec:

https://github.com/opengeospatial/sensorthings/issues/10
