### ISSUE TITLE
Linked HistoricalLocations to a Thing should be removed when a Thing is deleted

### ISSUE THREAD

**Issue by albertopq** [mozilla-sensorweb/sensorthings#192]
According to the compliance tests [1], it seems that, when deleting a Thing, is expecting all HistoricalLocations related to it to be removed as well. I don't see that constraint in table 25 [2].

@ferjm what do you think?

[1] https://github.com/opengeospatial/ets-sta10/blob/master/src/main/java/org/opengis/cite/sta10/createUpdateDelete/Capability2Tests.java#L1026
[2] http://docs.opengeospatial.org/is/15-078r6/15-078r6.html#table_25

**Comment by ferjm** [comment]
It looks like a bug in the spec. It makes sense to delete HistoricalLocations associated to a Thing being deleted. Could you file a bug in the spec, please?

**Comment by albertopq** [comment]
https://github.com/opengeospatial/sensorthings/issues/17
