### ISSUE TITLE
Error when expanding to multilevel models i.e ?$expand=Datastreams/Things

### ISSUE THREAD

**Issue by albertopq** [mozilla-sensorweb/sensorthings#200]
This feature is not implemented yet, but it should return an error. At the moment is timing out.

**Comment by albertopq** [comment]
Seeing this in the console:

`(node:85290) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'associations' of undefined`

**Comment by isabelrios** [comment]
Please see issue #198 it also appears there, the last two logs shown in the server logss

**Comment by albertopq** [comment]
Thanks @isabelrios ! That is a different one, though. That warning is being shown because of the way we are running the promises. It shouldn't affect the behavior.

**Comment by isabelrios** [comment]
Just to be sure :) I did not mean the warning in the title, but the same error you have seen, that is appearing in travis: 
node:2253) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 226): TypeError: Cannot read property 'associations' of undefined

(node:2253) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 227): TypeError: Cannot read property 'associations' of undefined
