### ISSUE TITLE
Implement geo.intersects or st_within

### ISSUE THREAD

**Issue by ferjm** [mozilla-sensorweb/sensorthings#227]
In order to allow an easier filtering by GPS coordinates, for example, to get the list of datastreams within a specific polygon, we need to implement the `geo.intersects` geospatial funciton or the `st_within` spatial relationship function as defined by the OGC standard.

**Comment by albertopq** [comment]
Depends on https://github.com/mozilla-sensorweb/node-odata-parser/issues/9
