### ISSUE TITLE
Form files would be needed to launch the ST Test Suite from Travis

### ISSUE THREAD

**Issue by isabelrios** [mozilla-sensorweb/sensorthings#46]
Here are some examples of those files for other Test Suites:
https://github.com/geoserver/geoserver-cite-tools/tree/master/forms

There is nothing for sta10. We would need to create those files to be able to launch the test suite in headless mode.

**Comment by isabelrios** [comment]
Seems that using this form file the tests can be launched headless mode:
<?xml version="1.0" encoding="UTF-8"?>
<values>
   <value key="uri">http://localhost:8080</value>
   <value key="doc"/>
   <value key="level">1</value>
</values>

**Comment by ferjm** [comment]
Fixed by #57
