### ISSUE TITLE
Implement preconditions to successfully launch ST test suite

### ISSUE THREAD

**Issue by isabelrios** [mozilla-sensorweb/sensorthings#47]
Here are the preconditions for the SenorThing API (STA) 1.0 Test Suite: http://cite.opengeospatial.org/te2/about/sta10/1.0/site/

According to the previous preconditions, there should be at least one entity per resource. It should be necessary to have data in the DB to test it.

**Comment by isabelrios** [comment]
This issue can be closed once #67 landed f0b88d3a
There is already a way to have data in the db. 
Once #57 lands the data will be populated before launching the Test Suite

**Comment by isabelrios** [comment]
Re-opening. Seems it is needed to send an specific JSON with the conditions to be tested in Conformance Leve 2 so the tests are executed.

**Comment by ferjm** [comment]
Fixed by #57
